import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter
import java.time.ZoneId

/*
 * Acuparse Weather Station
 *
 * Description:
 *   Polls Acuparse API JSON data and updates Hubitat attributes.
 *   Designed for use with Hubitat Package Manager (HPM).
 *
 * Author: RamSet
 * Version: 1.1.0
 * Date: 2025-04-24
 *
 * Changelog:
 *  v1.1.0 - Added system health check from /api/system/health endpoint.
 *          - Fetches system status, realtime status, and database info first.
 *          - Weather data updated after health check.
 *          - New attributes: systemStatus, realtimeStatus, databaseInfo.
 *          - Improved logging and handling of attribute updates.
 *          - Automatically converts timestamp fields (including lastUpdated,
 *            lightning_last_strike_ts, lightning_last_update, main_high_temp_recorded,
 *            main_lastUpdated, main_low_temp_recorded, main_moon_lastFull, main_moon_lastNew,
 *            main_moon_nextFull, main_moon_nextNew, main_moonrise, main_moonset, main_sunrise, main_sunset,
 *            and atlas_lastUpdated) into separate date and time attributes.
 * 
 *  v1.0.0 - Initial release.
 *          - Driver that pulls values from Acuparse API, including weather data.
 *          - Attributes for temperature, humidity, wind speed, light intensity, UV index, and lightning strike count.
 *          - Fully configurable polling interval and host/port settings.
 *          - Includes logging options (Debug, Info, Warn).
 *
 * HPM Metadata:
 * {
 *   "package": "Acuparse Weather Station",
 *   "author": "RamSet",
 *   "namespace": "custom",
 *   "location": "https://raw.githubusercontent.com/RamSet/hubitat/main/acuparse-weather-driver.groovy",
 *   "description": "Weather driver for polling Acuparse JSON data",
 *   "required": true
 * }
 */

metadata {
    definition(name: "Acuparse Weather Station", namespace: "custom", author: "RamSet") {
        capability "Sensor"
        capability "Polling"
        capability "Refresh"

        attribute "temperatureF", "number"
        attribute "humidity", "number"
        attribute "pressure_inHg", "number"
        attribute "windSpeedMPH", "number"
        attribute "lightIntensity", "number"
        attribute "uvIndex", "number"
        attribute "lightningStrikeCount", "number"
        attribute "lastUpdated", "string"
        attribute "systemStatus", "string"
        attribute "realtimeStatus", "string"
        attribute "databaseInfo", "string"
        
        // These attributes will be generated by converting timestamps
        attribute "main_lastUpdated_date", "string"
        attribute "main_lastUpdated_time", "string"
        attribute "atlas_lastUpdated_date", "string"
        attribute "atlas_lastUpdated_time", "string"
        attribute "lightning_last_strike_ts_date", "string"
        attribute "lightning_last_strike_ts_time", "string"
        attribute "lightning_last_update_date", "string"
        attribute "lightning_last_update_time", "string"
        attribute "main_high_temp_recorded_date", "string"
        attribute "main_high_temp_recorded_time", "string"
        attribute "main_low_temp_recorded_date", "string"
        attribute "main_low_temp_recorded_time", "string"
        attribute "main_moon_lastFull_date", "string"
        attribute "main_moon_lastFull_time", "string"
        attribute "main_moon_lastNew_date", "string"
        attribute "main_moon_lastNew_time", "string"
        attribute "main_moon_nextFull_date", "string"
        attribute "main_moon_nextFull_time", "string"
        attribute "main_moon_nextNew_date", "string"
        attribute "main_moon_nextNew_time", "string"
        attribute "main_moonrise_date", "string"
        attribute "main_moonrise_time", "string"
        attribute "main_moonset_date", "string"
        attribute "main_moonset_time", "string"
        attribute "main_sunrise_date", "string"
        attribute "main_sunrise_time", "string"
        attribute "main_sunset_date", "string"
        attribute "main_sunset_time", "string"
    }

    preferences {
        input name: "host", type: "string", title: "Device IP or Hostname", required: true
        input name: "port", type: "number", title: "Port (default 80)", required: false
        input name: "updateInterval", type: "number", title: "Polling interval (seconds)", defaultValue: 60
        input name: "logLevel", type: "enum", title: "Logging Level", 
            options: ["Off", "Info", "Debug", "Warn"], defaultValue: "Info"
    }
}

def installed() {
    initialize()
}

def updated() {
    unschedule()
    initialize()
}

def initialize() {
    logInfo "Initializing with interval: ${settings.updateInterval} seconds"
    if (settings.logLevel == "Debug") {
        logDebug "Debug logging will auto-disable in 5 minutes."
        runIn(300, disableDebugLogging)
    }
    scheduleNextPoll()
    poll()
}

def refresh() {
    poll()  // When refresh is triggered, poll() will process and update timestamp fields.
}

def scheduleNextPoll() {
    int seconds = settings.updateInterval ?: 60
    runIn(seconds, poll)
}

def poll() {
    if (!settings.host) {
        logWarn "Host/IP not configured."
        return
    }
    def targetPort = settings.port ?: 80
    def healthUri = "http://${settings.host}:${targetPort}/api/system/health"
    def weatherUri = "http://${settings.host}:${targetPort}/api/v1/json/dashboard/?main"
    
    // Check system health first
    def healthParams = [ uri: healthUri, contentType: "application/json" ]
    try {
        httpGet(healthParams) { healthResp ->
            if (healthResp?.status == 200 && healthResp?.data) {
                def healthData = healthResp.data
                updateAttr("systemStatus", healthData?.status)
                updateAttr("realtimeStatus", healthData?.realtime)
                updateAttr("databaseInfo", healthData?.database)
                // After health check, poll weather data
                pollWeatherData(weatherUri)
            } else {
                logWarn "Failed to fetch health data - Status: ${healthResp?.status}"
            }
        }
    } catch (e) {
        logWarn "Health check error: ${e.message}"
    }
}

private pollWeatherData(weatherUri) {
    def params = [ uri: weatherUri, contentType: "application/json" ]
    try {
        httpGet(params) { resp ->
            if (resp?.status == 200 && resp?.data) {
                def data = resp.data

                // Process all weather data attributes
                ["main", "atlas", "lightning"].each { section ->
                    data[section]?.each { key, value ->
                        def attrName = "${section}_${key}"
                        updateAttr(attrName, value)
                    }
                }

                // Update simplified (primary) attributes
                updateAttr("temperatureF", data?.main?.tempF)
                updateAttr("humidity", data?.main?.relH)
                updateAttr("pressure_inHg", data?.main?.pressure_inHg)
                updateAttr("windSpeedMPH", data?.main?.windSpeedMPH)
                updateAttr("lightIntensity", data?.atlas?.lightIntensity)
                updateAttr("uvIndex", data?.atlas?.uvIndex)
                updateAttr("lightningStrikeCount", data?.lightning?.strikecount)
                updateAttr("lastUpdated", data?.main?.lastUpdated)
                
                // Define lists of timestamp fields by section (assuming JSON keys are camelCase)
                def mainTimestampFields = ["lastUpdated", "high_temp_recorded", "low_temp_recorded", 
                    "moon_lastFull", "moon_lastNew", "moon_nextFull", "moon_nextNew", 
                    "moonrise", "moonset", "sunrise", "sunset"]
                def atlasTimestampFields = ["lastUpdated"]
                def lightningTimestampFields = ["last_strike_ts", "last_update"]

                // Process main timestamp fields
                mainTimestampFields.each { field ->
                    def value = data?.main?[field]
                    if (value) {
                        processTimestampField("main_${field}", value)
                    }
                }
                // Process atlas timestamp fields
                atlasTimestampFields.each { field ->
                    def value = data?.atlas?[field]
                    if (value) {
                        processTimestampField("atlas_${field}", value)
                    }
                }
                // Process lightning timestamp fields
                lightningTimestampFields.each { field ->
                    def value = data?.lightning?[field]
                    if (value) {
                        processTimestampField("lightning_${field}", value)
                    }
                }
            } else {
                logWarn "Failed to fetch weather data - Status: ${resp?.status}"
            }
        }
    } catch (e) {
        logWarn "Weather poll error: ${e.message}"
    }
    scheduleNextPoll()
}

private processTimestampField(attrName, timestamp) {
    try {
        // Parse the timestamp using ZonedDateTime (the format must handle the offset)
        def zdt = ZonedDateTime.parse(timestamp)
        // Convert to system default zone
        def localZdt = zdt.withZoneSameInstant(ZoneId.systemDefault())
        def dateStr = localZdt.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"))
        def timeStr = localZdt.format(DateTimeFormatter.ofPattern("HH:mm:ss"))
        // Update two separate attributes: one for the date and one for the time
        updateAttr("${attrName}_date", dateStr)
        updateAttr("${attrName}_time", timeStr)
    } catch (Exception e) {
        logWarn "Failed to parse timestamp '${timestamp}' for '${attrName}': ${e.message}"
    }
}

private updateAttr(name, value) {
    def current = device.currentValue(name)
    if (current?.toString() != value?.toString()) {
        sendEvent(name: name, value: value)
        logInfo "Updated ${name} = ${value}"
    } else {
        logDebug "No change for ${name}"
    }
}

private logDebug(msg) {
    if (settings.logLevel == "Debug") log.debug "[Acuparse] ${msg}"
}

private logInfo(msg) {
    if (settings.logLevel in ["Info", "Debug"]) log.info "[Acuparse] ${msg}"
}

private logWarn(msg) {
    if (settings.logLevel in ["Warn", "Debug"]) log.warn "[Acuparse] ${msg}"
}

def disableDebugLogging() {
    if (settings.logLevel == "Debug") {
        device.updateSetting("logLevel", [value: "Info", type: "enum"])
        logInfo "Debug logging disabled automatically after 5 minutes."
    }
}